### PR TITLE
Readme & Changelog

### PR DESCRIPTION
**Pull request by woprzech**

### CODE REVIEW

**Comment by michal-lipski** [comment]
I would add "motivation" section at the beginning of readme
Describe why this was created - what pains in regular testing via 'ng-mock' we stumbled upon.
Then describe how this library removes those problems.

**Comment by woprzech** [comment]
I am not sure that it is the best place for that. I think that it is a great idea for a blog post but not readme.

**Comment by krzysztof-jelski** [comment]
Having just gone through the new README, I very much missed 1 or 2 motivation statements at the beginning. Not knowing the library, I needed to analyze the example to see what does it allow me to do that is not possible in ng-mock kind of tests.

**Comment by woprzech** [comment]
Ok, I will write short comparison at the beginning

**Pull request merged**
